target1:yourcode.cpp
	g++ yourcode.cpp -o yourcode.out filecheck.h IO.h userfunctions.h -I /home/arushi/Desktop/sub2cop/new/include -L /home/arushi/Desktop/sub2cop/new/lib -lopenblas -lpthread -lgfortran

.PHONY: clean

clean:
	rm -f *.o yourcode.out
